# Generated by Django 5.2.6 on 2025-10-02 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_institute_location_institute_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institute',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='longitude',
        ),
    ]
