# Generated by Django 5.2.6 on 2025-10-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_institute_latitude_remove_institute_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='atitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
