# Generated by Django 5.2.6 on 2025-10-02 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_institute_atitude_institute_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institute',
            old_name='atitude',
            new_name='latitude',
        ),
    ]
