# Generated by Django 5.2.6 on 2025-10-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_rename_atitude_institute_latitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
