# Generated by Django 5.2.6 on 2025-10-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_institute_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='rating',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
