# Generated by Django 5.2.6 on 2025-10-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='mode',
            field=models.TextField(blank=True, null=True),
        ),
    ]
