# Generated by Django 5.2.6 on 2025-10-09 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_course_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='status',
        ),
    ]
