# Generated by Django 5.2.6 on 2025-10-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_remove_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
