# Generated by Django 5.2.6 on 2025-10-09 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_course_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='status',
        ),
    ]
