# Generated by Django 5.2.6 on 2025-10-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
