# Generated by Django 5.2.6 on 2025-10-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_institute_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_title',
            field=models.CharField(default='Untitled Course', max_length=100),
        ),
    ]
